-- 小组通知
DROP TABLE IF EXISTS `group_notices`;
CREATE TABLE `group_notices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '通知ID',
  `group_id` BIGINT NOT NULL COMMENT '小组ID',
  `title` VARCHAR(255) NOT NULL COMMENT '标题',
  `content` TEXT NOT NULL COMMENT '内容',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
